require 'pty'
require 'rubygems'
require 'terminal'

output = ""
read_io, write_io, pid = nil

dir = File.expand_path("examples.sh")

# spawn the process in a pseudo terminal so colors out outputted
read_io, write_io, pid = PTY.spawn("./examples.sh")

write_io.close

loop do
  fds, = IO.select([read_io], nil, nil, 5)
  if fds
    # should have some data to read
    begin
      chunk = read_io.read_nonblock(10240)
      if block_given?
        yield chunk
      end
      output += chunk
    rescue Errno::EAGAIN, Errno::EWOULDBLOCK
      # do select again
    rescue EOFError, Errno::EIO # EOFError from OSX, EIO is raised by ubuntu
      break
    end
  end
  # if fds are empty, timeout expired - run another iteration
end

read_io.close
Process.waitpid(pid)

examples = output.split("---").map do |example|
  rendered = Terminal.render(example.chomp.strip)
  %{<div class="code example"><pre class="before">#{example}</pre><pre class="after">#{rendered}</pre></div>}
end.join("\n")

template = File.read("template.html")

File.open("index.html", "w") do |file|
  file.write("<!--  DO NOT EDIT THIS FILE. GENERATED -->\n")
  file.write(template.gsub(/<!-- EXAMPLES HERE -->/, examples))
end
