#!/usr/bin/env ruby

# Usage:
#
#   script/memory_profile log.txt

$:.unshift(File.join(File.expand_path(File.dirname(__FILE__)), '..', 'lib'))

require 'terminal'
require 'memory_profiler'

log = $<.read

puts MemoryProfiler.report {
  Terminal.render(log)
}.pretty_print
