#!/usr/bin/env ruby

$:.unshift(File.join(File.expand_path(File.dirname(__FILE__)), '..', 'lib'))

require 'terminal'
require 'method_profiler'

screen_profiler = MethodProfiler.observe(Terminal::Screen)
render_profiler = MethodProfiler.observe(Terminal::Renderer)

def profile(file)
  output = File.read(file)
  basename = File.basename(file)
  iterations = 10

  puts "Rendering `#{basename}` #{iterations} times..."
  iterations.times { Terminal.render(output) }
end

if ARGV[0]
  profile(ARGV[0])
else
  Dir.glob("spec/fixtures/*.raw").each { |file| profile(file) }
end

puts screen_profiler.report
puts render_profiler.report
