#!/bin/bash
set -eu

version=$(make version)

echo "+++ :package: Downloading dist artifacts"

buildkite-agent artifact download "dist/*" dist

echo "+++ :rocket: Releasing $(version)"

docker-compose run --rm terminal github-release "v$version" dist/* \
  --commit "$BUILDKITE_COMMIT" \
  --tag "v$version" \
  --github-repository "buildkite/terminal"
